### ISSUE TITLE
Swagger para la API 

### ISSUE THREAD

**Issue by Nirigoyen** [Nirigoyen/modulo-usuarios-smartMove#14]

**Comment by RafaelGini** [comment]
Hacer una primera version del swagger de la appi. La puede hacer cualquiera. La idea es que tengamos un concepto base de la api. La misma tiene que poder cubrir el scope, osea estos puntos clave: 

1. Enpoints basicos: 

- "Login" a un usuario
- "Register" a un usuario
- "Autenticacion y autorizacion" de un usuario
- "Login de google" documentado tambien en el swagger. 

2. Endpoints funcionales

- Un endpoint que devuelva toda la data de un usuario en JSON tras haber comprobado las credenciales. 

3. Endpoints de administracion. 

- En el modulo de usuarios somos los responsables del ABM de usuarios y de manejar los permismos de los mismos. Asique tiene que haber toda una parte de la api que se encargue de poder administrar usuarios (por ejemplo, un administrador puede ver el listado de usuarios, dar de alta a usuarios, darle la baja logica a un usuario, cambiarle los permisos, etc)
**- Les dejo a ustedes que vayan poniendo los endpoint basicos que se les ocurra, y despues lo vamos completando mejor.**

**Comment by MicaSuarez915** [comment]
Dejo por acá el link del swagger que estuve haciendo como para tener una base, si quieren editarlo me avisan así los agrego.

https://app.swaggerhub.com/apis/Proyects_API_2/Proyecto_Login/1.0.0
